---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: evenkite
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      cleanup: true
      copr:
        - atim/starship
        - lilay/topgrade
    install:
      packages:
        - starship
        - fastfetch
        - hyfetch
        - topgrade
        - neovim
        - blackbox-terminal
        - btop
        - htop
        - nvtop
        - tree
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
        - ptyxis
        - gnome-tour
        - yelp
        - gnome-software

  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        install:
          - io.github.kolunmi.Bazaar
          - org.mozilla.firefox
          - org.gnome.Loupe
          - org.gnome.Decibels
          - org.gnome.Showtime
          - org.gnome.Papers
          - net.trowell.typesetter
          - com.github.PintaProject.Pinta
          - org.gnome.Calendar
          - io.github.flattool.Warehouse
          - com.github.tchx84.Flatseal
          - it.mijorus.gearlever
      - notify: false
        scope: user # Also add Flathub user repo, but no user packages

  - type: os-release
    properties:
      ID: evenkite
      ID_LIKE: fedora
      NAME: Evenkite Linux
      PRETTY_NAME: "Evenkite Linux"
      HOME_URL: "https://github.com/emberaine/evenkite/"
      BUG_REPORT_URL: "https://github.com/emberaine/evenkite/issues"
      DEFAULT_HOSTNAME: evenkite

  - type: script
    scripts:
      - cleanup.sh

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
