set allow-duplicate-recipes := true
set ignore-comments := true

_default:
    #!/usr/bin/bash
    /usr/bin/blujust --list --list-heading $'Available commands:\n' --list-prefix $' - '

# Imports
import? "/usr/share/bluebuild/justfiles/60-custom.just"